export const RESULT_LABELS:Record<string,{name:string;description:string;recommendations:string[]}>={
  R:{name:'Perfil Realista y Técnico',description:'Te atraen las actividades prácticas, los sistemas físicos y los problemas que producen resultados concretos y visibles.',recommendations:['Explora talleres, laboratorios y proyectos técnicos.','Compara carreras de ingeniería, tecnología, producción y trabajo de campo.']},
  I:{name:'Perfil Investigativo y Científico',description:'Disfrutas analizar información, formular preguntas, comprender causas y encontrar respuestas mediante evidencia.',recommendations:['Participa en proyectos de investigación y análisis.','Explora ciencias, salud, tecnología, datos y diagnóstico.']},
  A:{name:'Perfil Artístico y Creativo',description:'Valoras la expresión, la originalidad y la libertad para transformar ideas en propuestas con identidad propia.',recommendations:['Construye un portafolio con proyectos creativos.','Explora diseño, comunicación, arte, contenido y experiencias digitales.']},
  S:{name:'Perfil Social y de Servicio',description:'Te motiva comprender, orientar, enseñar y contribuir de manera directa al bienestar y desarrollo de otras personas.',recommendations:['Busca experiencias de voluntariado, enseñanza o acompañamiento.','Explora educación, psicología, salud y desarrollo humano.']},
  E:{name:'Perfil Emprendedor y de Liderazgo',description:'Te impulsa tomar iniciativa, movilizar personas, negociar y convertir oportunidades en proyectos y resultados.',recommendations:['Participa en proyectos donde puedas coordinar y decidir.','Explora negocios, dirección, ventas, derecho y emprendimiento.']},
  C:{name:'Perfil Organizador y de Gestión',description:'Te identificas con el orden, la precisión, la planificación y el manejo responsable de información y procesos.',recommendations:['Practica con presupuestos, planificación y control de proyectos.','Explora administración, finanzas, auditoría, banca y operaciones.']},
  VISUAL:{name:'Preferencia de aprendizaje visual',description:'Comprendes y recuerdas mejor cuando la información se presenta mediante imágenes, esquemas, colores, mapas y demostraciones.',recommendations:['Convierte tus apuntes en mapas conceptuales.','Usa diagramas, líneas de tiempo y códigos de color.']},
  AUDITORY:{name:'Preferencia de aprendizaje auditivo',description:'Procesas mejor las ideas al escucharlas, explicarlas con tus propias palabras y conversar sobre ellas.',recommendations:['Graba resúmenes breves y escúchalos.','Participa en debates o grupos de estudio.']},
  READING:{name:'Preferencia por lectura y escritura',description:'Aprendes con mayor claridad al leer, tomar apuntes, organizar conceptos y producir resúmenes escritos.',recommendations:['Elabora fichas, glosarios y resúmenes.','Reescribe los conceptos con tus propias palabras.']},
  KINESTHETIC:{name:'Preferencia de aprendizaje práctico',description:'Consolidas el aprendizaje cuando experimentas, practicas, construyes o aplicas lo aprendido en situaciones reales.',recommendations:['Transforma la teoría en ejercicios y proyectos.','Estudia en bloques breves con práctica activa.']},
  CREATIVITY:{name:'Creatividad y pensamiento original',description:'Tienes facilidad para imaginar alternativas, relacionar ideas y proponer soluciones diferentes ante situaciones nuevas.',recommendations:['Reserva espacios para explorar varias soluciones.','Registra tus ideas antes de evaluarlas.']},
  EMPATHY:{name:'Empatía y comprensión interpersonal',description:'Reconoces emociones y perspectivas ajenas, lo que favorece relaciones respetuosas y respuestas sensibles.',recommendations:['Practica la escucha sin interrumpir.','Confirma lo que comprendiste antes de aconsejar.']},
  DISCIPLINE:{name:'Disciplina y constancia',description:'Puedes sostener compromisos, organizar esfuerzos y avanzar hacia objetivos incluso cuando disminuye la motivación.',recommendations:['Divide objetivos grandes en acciones semanales.','Usa indicadores simples para revisar tu avance.']},
  LEADERSHIP:{name:'Liderazgo e iniciativa',description:'Tiendes a asumir responsabilidad, proponer dirección y ayudar a que un grupo avance hacia metas compartidas.',recommendations:['Define expectativas claras y escucha al equipo.','Delega responsabilidades con seguimiento respetuoso.']},
  RESILIENCE:{name:'Resiliencia y adaptación',description:'Cuentas con recursos para recuperarte, aprender de las dificultades y ajustar tu manera de actuar ante los cambios.',recommendations:['Identifica aprendizajes concretos después de un reto.','Pide apoyo oportunamente cuando lo necesites.']},
  COLLABORATION:{name:'Colaboración y trabajo en equipo',description:'Aportas a la confianza del grupo, compartes responsabilidades y buscas resultados que integren a otras personas.',recommendations:['Aclara acuerdos, funciones y tiempos.','Reconoce los aportes de los demás y ofrece ayuda específica.']}
}

export function resultMeta(code:string){return RESULT_LABELS[code]??{name:'Dimensión evaluada',description:'Esta dimensión representa una parte relevante de tu perfil.',recommendations:['Revisa tus respuestas y relaciónalas con experiencias concretas.']}}
