export type TestSource={label:string;url:string}
export type TestMeta={title:string;shortTitle:string;premiumCode?:string;notice?:string;purpose:string;method:string;sources:TestSource[]}
const riasec=[{label:'O*NET Interest Profiler · U.S. Department of Labor',url:'https://www.onetcenter.org/IP.html'},{label:'Manual técnico O*NET Interest Profiler',url:'https://www.onetcenter.org/dl_files/IP_Manual.pdf'}]
const learning=[{label:'Pashler et al. (2008), Learning Styles: Concepts and Evidence',url:'https://www.psychologicalscience.org/journals/pspi/j.1539-6053.2009.01038.x'}]
const strengths=[{label:'VIA Institute · investigación en fortalezas de carácter',url:'https://www.viacharacter.org/research/findings'}]
const autism=[{label:'Organización Mundial de la Salud · autismo',url:'https://www.who.int/news-room/fact-sheets/detail/autism-spectrum-disorders'},{label:'NICE · reconocimiento y evaluación en adultos',url:'https://www.nice.org.uk/guidance/cg142'}]
const adhd=[{label:'NIMH · TDAH en adultos',url:'https://www.nimh.nih.gov/health/publications/adhd-what-you-need-to-know'},{label:'OMS · CIE-11',url:'https://icd.who.int/browse/2026-01/mms/en'}]
const common=(title:string,shortTitle:string,purpose:string,method:string,sources:TestSource[],extra:Partial<TestMeta>={}):TestMeta=>({title,shortTitle,purpose,method,sources,...extra})
export const TEST_META:Record<string,TestMeta>={
 VOCATIONAL_FREE:common('Orientación Vocacional Gratuita','Orientación Vocacional','Explorar qué actividades y entornos ocupacionales despiertan mayor interés en ti.','Agrupa tus respuestas en seis áreas RIASEC. Es una orientación para comparar opciones, no una predicción de éxito profesional.',riasec,{premiumCode:'VOCATIONAL_PREMIUM'}),
 VOCATIONAL_PREMIUM:common('Perfil Vocacional Avanzado','Orientación Vocacional','Profundizar en tu combinación de intereses y obtener alternativas para investigar.','Utiliza más reactivos RIASEC para describir áreas principales y complementarias; debe combinarse con habilidades, valores, oportunidades y orientación profesional.',riasec),
 LEARNING_STYLE_FREE:common('Preferencias de Aprendizaje · Gratuito','Preferencias de Aprendizaje','Reconocer estrategias y formatos que hoy te resultan cómodos para estudiar.','Describe preferencias declaradas. La evidencia no respalda encasillar a una persona ni enseñar exclusivamente según un supuesto estilo fijo.',learning,{premiumCode:'LEARNING_STYLE_PREMIUM'}),
 LEARNING_STYLE_PREMIUM:common('Preferencias de Aprendizaje · Avanzado','Preferencias de Aprendizaje','Observar con más detalle tus hábitos y preferencias para diseñar experimentos de estudio.','El informe propone estrategias para probar y combinar; no afirma que adaptar la enseñanza a una etiqueta mejore por sí solo el aprendizaje.',learning),
 PERSONAL_STRENGTHS_FREE:common('Fortalezas Personales · Gratuito','Fortalezas Personales','Identificar recursos personales que percibes con mayor frecuencia en tu vida cotidiana.','Organiza autoobservaciones en dimensiones positivas para reflexión. No reproduce ni sustituye el instrumento VIA oficial.',strengths,{premiumCode:'PERSONAL_STRENGTHS_PREMIUM'}),
 PERSONAL_STRENGTHS_PREMIUM:common('Fortalezas Personales · Avanzado','Fortalezas Personales','Profundizar en recursos que puedes aplicar deliberadamente a metas y relaciones.','Compara dimensiones autopercibidas y ofrece sugerencias prácticas; el contexto influye en cómo se expresa cada fortaleza.',strengths),
 AUTISM_TRAITS_FREE:common('Exploración de indicadores TEA en adultos · Gratuita','Indicadores de TEA en adultos','Organizar experiencias de comunicación, flexibilidad, intereses y procesamiento sensorial.','Autoexploración educativa; no utiliza un punto de corte clínico ni confirma o descarta autismo.',autism,{premiumCode:'AUTISM_TRAITS_PREMIUM',notice:'Esta autoexploración no diagnostica autismo. Sólo organiza experiencias percibidas y puede ayudarte a decidir si deseas conversar con un profesional cualificado.'}),
 AUTISM_TRAITS_PREMIUM:common('Exploración de indicadores TEA en adultos · Avanzada','Indicadores de TEA en adultos','Revisar con más detalle experiencias persistentes en varios contextos.','La evaluación clínica requiere historia del desarrollo, impacto cotidiano y valoración profesional integral.',autism,{notice:'Este informe no confirma ni descarta autismo y no sustituye una evaluación clínica integral.'}),
 ADHD_TRAITS_FREE:common('Exploración de indicadores TDAH en adultos · Gratuita','Indicadores de TDAH en adultos','Organizar experiencias recientes de atención, inquietud, impulsividad y función ejecutiva.','Autoexploración educativa sin punto de corte diagnóstico; considera frecuencia en diferentes contextos.',adhd,{premiumCode:'ADHD_TRAITS_PREMIUM',notice:'Esta autoexploración no diagnostica TDAH. La frecuencia de estas experiencias también puede relacionarse con sueño, estrés, ansiedad, depresión u otras condiciones.'}),
 ADHD_TRAITS_PREMIUM:common('Exploración de indicadores TDAH en adultos · Avanzada','Indicadores de TDAH en adultos','Examinar patrones persistentes y su posible impacto cotidiano.','Un diagnóstico requiere inicio evolutivo, presencia en varios contextos, deterioro funcional y descarte de otras explicaciones.',adhd,{notice:'Este informe no confirma ni descarta TDAH y no sustituye una evaluación clínica integral.'})
}
const fallback=common('Evaluación personal','Evaluación personal','Conocerte mejor mediante una autoexploración estructurada.','Resultado orientativo basado en tus respuestas actuales.',[])
export function testMeta(code:string){return TEST_META[code]??fallback}
