import { useEffect,useState } from 'react'
import { Link,useNavigate,useParams } from 'react-router-dom'
import TestRunner from '../components/TestRunner'
import { getQuestions,submitFreeResult,submitPremiumResult } from '../services/testService'
import type { TestQuestion } from '../types/models'
import TestFeedback from '../components/TestFeedback'
import { recordTestCompletion } from '../services/feedbackService'
import { resultMeta } from '../lib/resultLabels'
import { testMeta } from '../lib/testMeta'
import { getTestCatalog, TestCatalogItem } from '../services/catalogService'

export default function GenericTestPage(){
 const {code=''}=useParams();const [questions,setQuestions]=useState<TestQuestion[]>([]);const [error,setError]=useState('');const [result,setResult]=useState<any[]>([]);const [started,setStarted]=useState(false);const [offer,setOffer]=useState<TestCatalogItem|null>(null);const navigate=useNavigate()
 useEffect(()=>{setStarted(false);getQuestions(code).then(setQuestions).catch(e=>setError(e.message))},[code])
 useEffect(()=>{getTestCatalog().then(items=>setOffer(items.find(item=>item.free_code===code)??null)).catch(()=>setOffer(null))},[code])
 useEffect(()=>{if(result.length)window.scrollTo({top:0,behavior:'smooth'})},[result])
 if(error)return <main className="page section"><div className="alert error">{error}</div><Link className="btn secondary" to="/tests">Volver</Link></main>
 const meta=testMeta(code)
 if(result.length)return <main className="page section result-page"><div className="page-hero compact"><span className="eyebrow">RESULTADO · {meta.shortTitle.toUpperCase()}</span><h1>{meta.title}</h1><h2>Tu dimensión principal: <span>{result[0].name}</span></h2><p>{result[0].description}</p><p className="result-disclaimer">{meta.notice??'Este resultado es orientativo: describe preferencias percibidas y no constituye un diagnóstico psicológico.'}</p></div><div className="areas-result-grid">{result.map(x=><article className="score-card" key={x.code}><div className="score-number">{x.percent}%</div><h2>{x.name}</h2><p>{x.description}</p><div className="score-bar"><i style={{width:`${x.percent}%`}}/></div></article>)}</div><section className="admin-card"><h2>Cómo aprovechar tu resultado principal</h2><ul>{resultMeta(result[0].code).recommendations.map((item:string)=><li key={item}>{item}</li>)}</ul></section><Methodology meta={meta}/>{meta.premiumCode&&<section className="upgrade-banner"><div><span className="eyebrow">PROFUNDIZA TU RESULTADO</span><h2>¿Quieres un análisis más completo?</h2><p>La versión avanzada incluye más preguntas, un perfil más detallado y conserva cada intento en tu cuenta.</p></div><Link className="btn primary large" to={`/acceso/${meta.premiumCode}`}>Probar versión avanzada →</Link></section>}<TestFeedback testCode={code}/></main>
 if(!questions.length)return <main className="page section"><div className="loading">Preparando evaluación…</div></main>
 const finish=async(answers:Record<string,number>)=>{const groups=new Map<string,{total:number,count:number}>();questions.forEach(q=>{const g=groups.get(q.dimension_code)||{total:0,count:0};g.total+=answers[q.id]||0;g.count++;groups.set(q.dimension_code,g)});const results=[...groups].map(([dimension,g])=>{const detail=resultMeta(dimension);return {code:dimension,name:detail.name,score:g.total,maxScore:g.count*4,percent:Math.round(g.total/(g.count*4)*100),description:detail.description,careers:[]}}).sort((a,b)=>b.percent-a.percent);recordTestCompletion(code).catch(()=>{});if(code.endsWith('_PREMIUM')){const saved=await submitPremiumResult({testCode:code,answers,results:results as any});navigate(`/resultado/${saved.evaluationId}`)}else{const saved=await submitFreeResult({testCode:code,answers});if(saved)navigate(`/resultado/${saved.evaluationId}`);else setResult(results)}}
 if(!started)return <main className="page section"><section className="test-intro admin-card"><span className="eyebrow">ANTES DE COMENZAR</span><h1>{meta.title}</h1><h2>¿Qué explora?</h2><p>{meta.purpose}</p><h2>Cómo se interpreta</h2><p>{meta.method}</p><div className="intro-facts"><span>{questions.length} preguntas</span><span>Respuestas confidenciales</span><span>Resultado orientativo</span></div><Methodology meta={meta}/><div className="test-mode-actions"><button className="btn primary large" onClick={()=>{setStarted(true);window.scrollTo({top:0})}}>Comenzar test gratuito →</button>{meta.premiumCode&&<Link className="btn secondary large advanced-intro-cta" to={`/acceso/${meta.premiumCode}`}><span>Elegir test avanzado</span><strong>{offer?`${offer.price} ${offer.currency}`:'Ver precio'}</strong></Link>}</div>{meta.premiumCode&&<p className="test-mode-note">Puedes comenzar gratis ahora o elegir la versión avanzada con más preguntas y un informe más detallado.</p>}</section></main>
 return <TestRunner title={meta.title} questions={questions} onFinish={finish}/>
}

export function Methodology({meta}:{meta:ReturnType<typeof testMeta>}){return <section className="methodology"><h2>Metodología y fuentes</h2><p>{meta.method}</p>{meta.sources.length>0&&<ul>{meta.sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a></li>)}</ul>}<p className="result-disclaimer">MentesModernas es una herramienta educativa de autoexploración; no emite diagnósticos ni reemplaza asesoramiento profesional.</p></section>}
