// Editorial instrument v1.0. Not an O*NET instrument or validated psychometric scale.
export const CAREER_CODE = 'VOCATIONAL_AI_2026_PREMIUM'
export const CAREER_DATE = '2026-09-08'
export const CAREER_SOURCES = [
  {label:'OIT · Employment and Social Trends 2026',url:'https://www.ilo.org/publications/flagship-reports/employment-and-social-trends-2026'},
  {label:'OCDE · AI and skills: What we know so far (2026)',url:'https://www.oecd.org/en/publications/ai-and-skills_f843b352-en/full-report.html'},
  {label:'OIT–NASK · Exposición ocupacional a IA generativa (2025)',url:'https://www.ilo.org/publications/generative-ai-and-jobs-2025-update'},
  {label:'Foro Económico Mundial · Future of Jobs 2025, horizonte 2030',url:'https://www.weforum.org/publications/the-future-of-jobs-report-2025/in-full/2-jobs-outlook/'},
  {label:'O*NET · Marco de intereses ocupacionales RIASEC',url:'https://www.onetcenter.org/IP.html'}
]
export const CAREER_DIMENSIONS:Record<string,{name:string;description:string;action:string}> = {
 R:{name:'Práctica y tecnología física',description:'Interés por construir, mantener y mejorar sistemas del mundo físico.',action:'Visita un taller o laboratorio y realiza una práctica supervisada.'},
 I:{name:'Investigación y análisis',description:'Interés por explicar problemas y contrastar hipótesis con evidencia.',action:'Analiza un conjunto de datos y documenta sus limitaciones.'},
 A:{name:'Creación y diseño',description:'Interés por imaginar propuestas y diseñar experiencias con significado.',action:'Crea un prototipo y pide retroalimentación a tres personas.'},
 S:{name:'Cuidado y enseñanza',description:'Interés por acompañar, enseñar y atender necesidades humanas.',action:'Entrevista a un profesional de salud o educación sobre su trabajo cotidiano.'},
 E:{name:'Iniciativa y coordinación',description:'Interés por negociar, coordinar personas y desarrollar proyectos.',action:'Organiza un pequeño proyecto con una meta y responsabilidades claras.'},
 C:{name:'Organización y calidad',description:'Interés por ordenar información, verificar procesos y mantener precisión.',action:'Diseña una lista de control y úsala para revisar un proceso real.'},
 AI_LITERACY:{name:'Uso crítico de IA',description:'Hábitos declarados para usar IA con verificación y protección de datos; no mide destreza técnica.',action:'Compara una respuesta de IA con dos fuentes originales y registra errores.'},
 JUDGMENT:{name:'Criterio y evidencia',description:'Disposición declarada a contrastar información antes de decidir.',action:'Separa hechos, supuestos y dudas en una decisión de estudio.'},
 HUMAN:{name:'Comunicación y colaboración',description:'Hábitos declarados de escucha, explicación y colaboración.',action:'Explica una idea a alguien de otro campo y comprueba qué comprendió.'},
 ADAPT:{name:'Aprendizaje y adaptación',description:'Disposición declarada para practicar, recibir comentarios y cambiar de estrategia.',action:'Reserva dos sesiones semanales para aprender una herramienta nueva.'},
 ETHICS:{name:'Responsabilidad y contexto',description:'Atención declarada a consecuencias, privacidad y supervisión humana.',action:'Elabora reglas de privacidad y revisión humana para un proyecto con IA.'},
 SYSTEMS:{name:'Pensamiento sistémico',description:'Interés declarado por relaciones entre tecnología, personas, recursos y entorno.',action:'Dibuja cómo un cambio técnico afecta a clientes, trabajadores y recursos.'}
}
export const CAREER_BANK:Record<string,string[]> = {
 R:['Me atrae instalar y comprobar equipos que deben funcionar en condiciones reales.','Disfrutaría investigar por qué una máquina o un dispositivo dejó de funcionar.','Me interesa trabajar con herramientas para construir o reparar objetos.','Me gustaría mejorar sistemas de energía, agua o producción mediante trabajo práctico.'],
 I:['Me interesa investigar las causas de un problema antes de proponer una solución.','Disfrutaría comparar datos para comprobar si una explicación es correcta.','Me atrae diseñar experimentos y revisar qué significan sus resultados.','Me gustaría estudiar problemas científicos o tecnológicos aunque no tengan una respuesta inmediata.'],
 A:['Me interesa diseñar experiencias que resulten claras y significativas para otras personas.','Disfrutaría crear propuestas visuales o narrativas con un punto de vista propio.','Me atrae explorar varias ideas antes de elegir una solución de diseño.','Me gustaría transformar necesidades poco claras en un prototipo creativo.'],
 S:['Me interesa acompañar a personas que necesitan atención o apoyo.','Disfrutaría enseñar un tema y adaptar la explicación a quien aprende.','Me atrae trabajar directamente con personas para mejorar su bienestar.','Me gustaría comprender las necesidades de una comunidad antes de intervenir.'],
 E:['Me interesa coordinar un equipo para llevar una idea a la práctica.','Disfrutaría negociar acuerdos entre personas con prioridades diferentes.','Me atrae detectar necesidades y desarrollar un servicio para resolverlas.','Me gustaría asumir decisiones y responsabilidad por el avance de un proyecto.'],
 C:['Me interesa revisar información para encontrar errores o inconsistencias.','Disfrutaría organizar recursos y plazos para que un proceso sea confiable.','Me atrae comprobar que un trabajo cumple criterios de calidad.','Me gustaría mantener registros precisos que permitan justificar una decisión.'],
 AI_LITERACY:['Cuando uso o pruebo IA, comparo su respuesta con información verificable.','Puedo describir con claridad una tarea antes de pedir ayuda a una herramienta digital.','Antes de introducir información en una IA, reviso si contiene datos privados.','Me interesa practicar con herramientas de IA y comprobar dónde se equivocan.'],
 JUDGMENT:['Busco la fuente original cuando una afirmación influye en una decisión importante.','Cambio mi explicación cuando encuentro evidencia que la contradice.','Distingo entre un dato observado y una suposición al resolver un problema.','Comparo alternativas antes de aceptar la primera solución que parece funcionar.'],
 HUMAN:['Compruebo que entendí a otra persona antes de ofrecer una solución.','Adapto mi explicación cuando alguien no conoce los términos que utilizo.','Puedo expresar un desacuerdo sin dejar de escuchar a la otra persona.','Cuando colaboro, aclaro responsabilidades y pido ayuda si la necesito.'],
 ADAPT:['Puedo mantener una rutina breve para aprender algo nuevo.','Uso los comentarios sobre mi trabajo para intentar una mejora concreta.','Si una herramienta cambia, busco una manera de aprender lo necesario.','Pruebo una estrategia diferente cuando la anterior no me permite avanzar.'],
 ETHICS:['Antes de automatizar una decisión, pienso quién podría verse perjudicado.','Reconozco cuándo una tarea requiere la revisión de una persona cualificada.','Me importa poder explicar por qué se tomó una decisión asistida por tecnología.','Reviso si tengo permiso para utilizar datos o materiales de otras personas.'],
 SYSTEMS:['Me interesa entender cómo un cambio en una parte afecta al resto de un proceso.','Al proponer una mejora, considero el tiempo y los recursos que exige mantenerla.','Pienso en necesidades locales antes de copiar una solución usada en otro país.','Me interesa relacionar decisiones tecnológicas con su impacto social y ambiental.']
}
export type CareerPath={name:string;areas:string[];trend:string;human:string;change:string;route:string;experiment:string;source:number}
export const CAREER_PATHS:CareerPath[] = [
 {name:'Energía y mantenimiento electromecánico',areas:['R','I'],trend:'La transición energética abre necesidades técnicas; la demanda concreta depende de inversión local.',human:'Instalación, seguridad y diagnóstico en terreno.',change:'IA para monitoreo y mantenimiento predictivo; algunas tareas se automatizan.',route:'Formación técnica eléctrica/electromecánica o ingeniería y certificaciones de seguridad.',experiment:'Investiga tres empresas locales y sus requisitos de contratación.',source:3},
 {name:'Agrotecnología, agua y adaptación climática',areas:['R','C'],trend:'La adaptación climática y la producción de alimentos impulsan cambios en procesos y competencias.',human:'Trabajo de campo, condiciones locales y operación segura.',change:'Sensores y análisis automatizado apoyan decisiones agronómicas.',route:'Técnico agropecuario, agronomía, gestión de agua o ingeniería ambiental.',experiment:'Conversa con un productor sobre un problema que puedas medir.',source:3},
 {name:'Datos e ingeniería de IA aplicada',areas:['I','C'],trend:'Datos e IA figuran entre las áreas tecnológicas de crecimiento esperado hasta 2030.',human:'Formular problemas, evaluar calidad y verificar resultados.',change:'La generación de código y análisis rutinario cambia el trabajo de entrada.',route:'Estadística, informática o formación técnica con matemáticas y proyectos verificables.',experiment:'Analiza datos abiertos y explica qué conclusiones no permiten obtener.',source:3},
 {name:'Ciberseguridad y sistemas confiables',areas:['I','R'],trend:'La seguridad digital aparece entre las competencias de mayor crecimiento esperado.',human:'Investigación de incidentes, criterio y responsabilidad operativa.',change:'La IA apoya detección y también amplía amenazas.',route:'Redes, sistemas o informática, laboratorios legales y seguridad defensiva.',experiment:'Configura un laboratorio propio y documenta una mejora defensiva.',source:3},
 {name:'Diseño de servicios y experiencia de usuario',areas:['A','S'],trend:'La combinación de creatividad y competencias humanas sigue siendo relevante; esto no garantiza crecimiento de cada puesto de diseño.',human:'Investigar necesidades, accesibilidad y contexto cultural.',change:'La producción visual genérica está expuesta a automatización.',route:'Diseño, comunicación o tecnología con investigación de usuarios y portafolio.',experiment:'Rediseña un formulario tras observar a tres usuarios voluntarios.',source:1},
 {name:'Diseño de producto y prototipado',areas:['A','R'],trend:'La digitalización exige combinar diseño y conocimiento del dominio; las oportunidades varían por sector.',human:'Definir restricciones reales y comprobar que el producto sirve.',change:'IA acelera bocetos y variaciones; requiere validación de calidad.',route:'Diseño industrial, ingeniería o formación técnica en prototipado.',experiment:'Construye un prototipo sencillo y registra las mejoras tras probarlo.',source:1},
 {name:'Enfermería y rehabilitación',areas:['S','I'],trend:'El envejecimiento y las necesidades de cuidados sostienen la demanda prevista en salud.',human:'Atención presencial, confianza y responsabilidad clínica.',change:'IA puede apoyar documentación y análisis, con supervisión profesional.',route:'Carrera acreditada de enfermería o rehabilitación y habilitación profesional local.',experiment:'Entrevista a un profesional sobre turnos, formación y exigencias reales.',source:3},
 {name:'Educación y formación continua',areas:['S','A'],trend:'Los cambios demográficos y la actualización de competencias impulsan necesidades educativas.',human:'Acompañamiento, motivación y adaptación al alumno.',change:'IA produce materiales; el diseño pedagógico y la evaluación requieren criterio.',route:'Educación o especialidad de dominio con formación pedagógica.',experiment:'Prepara una microclase y comprueba qué pudo aplicar quien aprendió.',source:3},
 {name:'Gestión de proyectos de transformación',areas:['E','C'],trend:'La adopción de IA cambia procesos y requiere competencias de gestión y coordinación.',human:'Acuerdos, prioridades y manejo de conflictos.',change:'Seguimiento e informes rutinarios pueden automatizarse.',route:'Administración, ingeniería o experiencia sectorial más gestión de proyectos.',experiment:'Organiza un proyecto pequeño con alcance, presupuesto y revisión final.',source:1},
 {name:'Emprendimiento de servicios especializados',areas:['E','S'],trend:'La IA puede complementar trabajo experto; la viabilidad depende de clientes y contexto, no de una tendencia por sí sola.',human:'Comprender clientes, generar confianza y responder por el servicio.',change:'Servicios genéricos enfrentan competencia y automatización.',route:'Formación en un oficio o especialidad más ventas consultivas y costos.',experiment:'Entrevista a cinco posibles clientes antes de invertir.',source:1},
 {name:'Calidad, auditoría y gobernanza de datos',areas:['C','I'],trend:'La adopción responsable de IA exige evaluar riesgos y procesos; es una aplicación editorial de la evidencia, no una previsión de vacantes.',human:'Trazabilidad, juicio y responsabilidad por controles.',change:'Revisión documental repetitiva expuesta a automatización.',route:'Auditoría, sistemas, derecho o gestión de calidad con especialización en datos.',experiment:'Diseña una lista de revisión de privacidad y calidad para datos ficticios.',source:1},
 {name:'Operaciones y logística con analítica',areas:['C','E'],trend:'Tecnología y cambios en cadenas de suministro transforman la organización del trabajo.',human:'Resolver excepciones y coordinar proveedores y equipos.',change:'Planificación repetitiva y registros se automatizan progresivamente.',route:'Logística, ingeniería industrial o formación técnica en operaciones.',experiment:'Mapea un proceso de entrega y propone una mejora medible.',source:3}
]
export function buildCareerReport(questions:{id:string;dimension_code:string}[],answers:Record<string,number>){
 if(questions.length!==48||Object.keys(answers).length!==48)throw new Error('La evaluación requiere sus 48 respuestas.')
 const groups:Record<string,{sum:number;count:number}>={}
 for(const q of questions){const value=answers[q.id];if(!Object.hasOwn(CAREER_DIMENSIONS,q.dimension_code)||typeof value!=='number'||!Number.isInteger(value)||value<0||value>4)throw new Error('Respuesta o dimensión inválida.');const g=groups[q.dimension_code]??={sum:0,count:0};g.sum+=value;g.count++}
 if(Object.keys(groups).length!==12||Object.values(groups).some(g=>g.count!==4))throw new Error('El instrumento requiere cuatro preguntas por dimensión.')
 const all=Object.entries(groups).map(([code,g])=>({code,name:CAREER_DIMENSIONS[code].name,description:CAREER_DIMENSIONS[code].description,score:g.sum,maxScore:16,percent:Math.round(g.sum/16*100),careers:[] as string[],recommendations:[CAREER_DIMENSIONS[code].action]}))
 const results=all.filter(x=>x.code.length===1).sort((a,b)=>b.percent-a.percent||a.code.localeCompare(b.code))
 const skills=all.filter(x=>x.code.length>1).sort((a,b)=>a.percent-b.percent||a.code.localeCompare(b.code))
 const interest=Object.fromEntries(results.map(x=>[x.code,x.percent]))
 const pathways=CAREER_PATHS.map(p=>({...p,affinity:Math.round(p.areas.reduce((s,a)=>s+interest[a],0)/p.areas.length)})).sort((a,b)=>b.affinity-a.affinity||a.name.localeCompare(b.name)).slice(0,6)
 const flat=results[0].percent-results[5].percent<13
 return {results,skills,pathways,primaryArea:results[0].code,secondaryArea:results[1].code,summary:flat?'Tus intereses aparecen poco diferenciados. Explora varias experiencias antes de priorizar una carrera; los empates no indican superioridad de una opción.':`Tus intereses más destacados son ${results[0].name} y ${results[1].name}. Usa las rutas sugeridas como hipótesis para investigar.`,highCompatibility:[],mediumCompatibility:[],recommendations:skills.slice(0,3).flatMap(x=>x.recommendations),methodVersion:'2026.1',evidenceDate:CAREER_DATE,sources:CAREER_SOURCES,generatedAt:new Date().toISOString(),notice:'La afinidad es el promedio de dos áreas de interés, no una probabilidad de empleo ni de supervivencia a la IA. Las habilidades son autoobservaciones, no una prueba de aptitud. Instrumento editorial sin validación psicométrica; ninguna carrera está garantizada. Contrasta formación, costos, habilitación y vacantes en Bolivia o tu país.'}
}
