-- Biblioteca editorial equilibrada: adolescencia, relaciones, estudio, bienestar y neurodiversidad.
insert into public.site_content(key,value,is_active) values('news',jsonb_build_object('articles',jsonb_build_array(
 jsonb_build_object('id','adolescencia-identidad','category','ADOLESCENCIA','title','Crecer también es explorar quién eres','excerpt','La adolescencia combina cambios físicos, emocionales y sociales. Explorar identidad, pertenencia y autonomía es parte del proceso y se beneficia de entornos seguros.','read_time','5 min','source','Organización Mundial de la Salud','url','https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health','link_label','Leer fuente oficial'),
 jsonb_build_object('id','primer-desamor','category','RELACIONES','title','El primer desamor: sentir, cuidarse y volver a conectar','excerpt','Una ruptura puede traer tristeza, enojo y confusión. Dar espacio a lo que sientes, sostener rutinas y hablar con alguien de confianza ayuda a atravesar el proceso.','read_time','5 min','source','MentesModernas · orientación educativa','url','https://www.who.int/data/gho/indicator-metadata-registry/imr-details/10536','link_label','Por qué hablar ayuda'),
 jsonb_build_object('id','amistades-limites','category','VÍNCULOS','title','Amistades sanas y límites que también cuidan','excerpt','Poder decir que no, respetar diferencias y reparar desacuerdos fortalece los vínculos. Un límite claro no es rechazo: comunica qué necesitas.','read_time','4 min','source','UNICEF Parenting','url','https://www.unicef.org/parenting/mental-health','link_label','Explorar recursos'),
 jsonb_build_object('id','presion-estudios','category','ESTUDIO','title','Cuando estudiar se convierte en demasiada presión','excerpt','Dividir tareas, descansar y pedir apoyo puede reducir la sensación de bloqueo. Tu rendimiento es información sobre un momento, no una medida completa de tu valor.','read_time','5 min','source','OMS','url','https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health','link_label','Leer sobre bienestar adolescente'),
 jsonb_build_object('id','sueno-aprendizaje','category','APRENDIZAJE','title','Dormir también forma parte de aprender','excerpt','El sueño favorece atención, memoria y regulación emocional. Una rutina realista suele aportar más que estudiar toda la noche.','read_time','4 min','source','CDC','url','https://www.cdc.gov/sleep/about/index.html','link_label','Ver recomendaciones'),
 jsonb_build_object('id','redes-comparacion','category','BIENESTAR DIGITAL','title','Redes sociales sin vivir comparándote','excerpt','Lo que ves en pantalla es una selección. Observar cómo cambia tu ánimo, silenciar contenido y proteger momentos sin conexión ayuda a recuperar perspectiva.','read_time','5 min','source','American Psychological Association','url','https://www.apa.org/topics/social-media-internet/health-advisory-adolescent-social-media-use','link_label','Consultar orientación'),
 jsonb_build_object('id','elegir-carrera','category','ORIENTACIÓN','title','Elegir carrera no exige tener toda la vida resuelta','excerpt','Una buena decisión combina intereses, habilidades, valores, posibilidades reales y experimentación. Investigar y conversar vale más que perseguir una respuesta perfecta.','read_time','6 min','source','O*NET Resource Center','url','https://www.onetcenter.org/IP.html','link_label','Explorar intereses'),
 jsonb_build_object('id','ansiedad-pedir-ayuda','category','SALUD MENTAL','title','Cómo reconocer que necesitas apoyo adicional','excerpt','Si el malestar persiste, interfiere con estudio, sueño o relaciones, o aparecen ideas de hacerte daño, hablar con un adulto de confianza y un profesional es importante.','read_time','5 min','source','NIMH','url','https://www.nimh.nih.gov/health/find-help','link_label','Encontrar ayuda'),
 jsonb_build_object('id','fortalezas','category','AUTOCONOCIMIENTO','title','Tus fortalezas también se entrenan','excerpt','Reconocer recursos personales permite usarlos con intención. Una fortaleza no es una etiqueta fija: cambia según el contexto y puede expresarse de distintas maneras.','read_time','5 min','source','VIA Institute','url','https://www.viacharacter.org/research/findings','link_label','Explorar investigación'),
 jsonb_build_object('id','neurodiversidad','category','NEURODIVERSIDAD','title','Neurodiversidad: diferencias, contexto y apoyos','excerpt','Atención, comunicación, aprendizaje y percepción varían entre personas. Comprender necesidades concretas evita reducir a alguien a una etiqueta.','read_time','6 min','source','Organización Mundial de la Salud','url','https://www.who.int/news-room/fact-sheets/detail/autism-spectrum-disorders','link_label','Leer fuente oficial'),
 jsonb_build_object('id','tdah-contexto','category','TDAH','title','TDAH más allá de “distraerse”','excerpt','La atención, la impulsividad y la organización deben evaluarse a lo largo del tiempo y en varios contextos. Sueño, estrés y otras condiciones también importan.','read_time','6 min','source','NIMH','url','https://www.nimh.nih.gov/health/publications/adhd-what-you-need-to-know','link_label','Leer guía oficial'),
 jsonb_build_object('id','conversaciones-dificiles','category','COMUNICACIÓN','title','Cómo empezar una conversación difícil','excerpt','Elegir un momento tranquilo, hablar desde tu experiencia y pedir algo concreto puede hacer más segura una conversación sobre emociones, límites o decisiones.','read_time','4 min','source','OMS · bienestar adolescente','url','https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health','link_label','Conocer factores protectores')
)),true) on conflict(key) do update set value=excluded.value,is_active=true,updated_at=now();
