insert into public.site_content(key,value,is_active) values
('site_stats','{"completed_tests":13433,"active_users":14533,"effectiveness":83}'::jsonb,true),
('news',jsonb_build_object('articles',jsonb_build_array(
  jsonb_build_object('id','neurodiversidad','category','NEURODIVERSIDAD','title','Neurotípico y neurodivergente: distintas formas de procesar el mundo','excerpt','Ser neurotípico describe patrones de desarrollo frecuentes; neurodivergencia reúne variaciones naturales en atención, comunicación, aprendizaje y percepción. Ninguna etiqueta resume por completo a una persona.','read_time','5 min de lectura'),
  jsonb_build_object('id','autismo','category','ESPECTRO AUTISTA','title','Autismo: comprender el espectro desde las fortalezas y los apoyos','excerpt','El espectro autista incluye experiencias diversas en comunicación, intereses y procesamiento sensorial. Un entorno accesible y apoyos individualizados pueden favorecer participación y bienestar.','read_time','6 min de lectura'),
  jsonb_build_object('id','tdah','category','TDAH','title','TDAH más allá de la distracción','excerpt','El TDAH puede influir en atención, regulación de impulsos, motivación y organización. Las estrategias externas, rutinas flexibles y acompañamiento profesional pueden marcar una diferencia.','read_time','5 min de lectura'),
  jsonb_build_object('id','dislexia','category','APRENDIZAJE','title','Dislexia: aprender a leer el talento de otra manera','excerpt','La dislexia afecta principalmente la precisión o fluidez lectora, pero no define la inteligencia. La enseñanza explícita y los formatos accesibles ayudan a demostrar capacidades.','read_time','4 min de lectura'),
  jsonb_build_object('id','altas-capacidades','category','ALTAS CAPACIDADES','title','Altas capacidades y necesidades que también merecen apoyo','excerpt','El potencial elevado puede convivir con intensidad emocional, aburrimiento o desarrollo desigual. Reconocer necesidades reales evita reducir la experiencia a una calificación.','read_time','5 min de lectura'),
  jsonb_build_object('id','bienestar-digital','category','BIENESTAR DIGITAL','title','Atención, descanso y tecnología: construir hábitos sostenibles','excerpt','Dormir, alternar periodos de concentración y reducir interrupciones puede mejorar el aprendizaje. La meta no es eliminar la tecnología, sino usarla con intención.','read_time','4 min de lectura')
)),true)
on conflict(key) do update set value=excluded.value,is_active=true,updated_at=now();
